---
abstract: 'Create objects from hashes on the fly'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Objectify
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Hash::Objectified:
    file: lib/Hash/Objectify.pm
    version: 0.002
  Hash::Objectify:
    file: lib/Hash/Objectify.pm
    version: 0.002
requires:
  Carp: 0
  Class::XSAccessor: 0
  Scalar::Util: 0
  Sub::Install: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/hash-objectify/issues
  homepage: https://metacpan.org/release/Hash-Objectify
  repository: git://github.com/dagolden/hash-objectify.git
version: 0.002
x_authority: cpan:DAGOLDEN
